import React from "react";
import { formatarCentavos } from "./FormularioPedido.jsx";

const rotulos = { anterior: "Antes", novo: "Depois", nome: "Nome", quantidade: "Quantidade", itens: "Itens", composicao: "Composição", endereco: "Endereço", desconto: "Desconto", percentual: "Percentual", valorFixo: "Valor fixo (R$)", ordem: "Ordem do desconto", motivo: "Motivo", nomeAutor: "Responsável", realizadoEm: "Data do pagamento", totalCentavos: "Total", subtotalCentavos: "Subtotal", descontoCentavos: "Desconto aplicado", precoPacoteCentavos: "Preço por pacote", valorCentavos: "Valor", observacoes: "Observações", situacao: "Situação", tipo: "Tipo", forma: "Forma", dataEntrega: "Data agendada", horarioEntrega: "Horário", cliente: "Cliente", multiploMinimo: "Unidades por pacote", tipoEntrega: "Tipo de atendimento", camposAlterados: "Campos alterados", versaoCatalogo: "Versão do cadastro", limiteDescontoOriginal: "Limite original (%)", limiteOriginal: "Limite original (%)", pagamento: "Pagamento", estorno: "Estorno", codigoComanda: "Comanda", detalhesPersonalizacao: "Personalização", avisos: "Avisos", mensagem: "Mensagem", impedimentos: "Pendências", proposta: "Proposta", rua: "Rua", numero: "Número", bairro: "Bairro", complemento: "Complemento", pontoReferencia: "Referência", cep: "CEP", cidade: "Cidade", estado: "Estado", telefone: "Telefone" };
const oculto = (chave) => /^id[A-Z]/.test(chave) || ["chaveItem", "assinatura", "assinaturaCatalogo", "urlFoto"].includes(chave);
export default function ValoresHistoricoPedido({ valor }) {
  if (valor === null || valor === undefined || valor === "") return <span>Não informado</span>;
  if (Array.isArray(valor)) return <ul className="space-y-2 border-l pl-3">{valor.map((item, indice) => <li key={indice}><ValoresHistoricoPedido valor={item} /></li>)}</ul>;
  if (typeof valor !== "object") return <span>{typeof valor === "boolean" ? (valor ? "Sim" : "Não") : String(valor).replaceAll("_", " ")}</span>;
  return <dl className="space-y-1">{Object.entries(valor).filter(([chave]) => !oculto(chave)).map(([chave, conteudo]) => <div key={chave}><dt className="font-medium">{rotulos[chave] || chave.replace(/([A-Z])/g, " $1")}</dt><dd className="pl-3 text-slate-600">{chave === "foto" ? (conteudo ? "Foto de referência preservada" : "Sem foto") : chave.endsWith("Centavos") ? formatarCentavos(conteudo) : <ValoresHistoricoPedido valor={conteudo} />}</dd></div>)}</dl>;
}
